sudo: false
language: node_js
node_js:
  - 12 
cache: npm
branches:
  only:
    - hexo # 当hexo分支有新的commit时执行 
install: npm install hexo-generator-sitemap --save
script:
  - hexo generate 
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: master # 注意这里是部署到master, 默认是到gh-pages
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: hexo
  local-dir: public
